export const GET_ALL_ADMIN_REQUEST = "GET_ALL_ADMIN_REQUEST";
export const GET_ALL_ADMIN_SUCCESS = "GET_ALL_ADMIN_SUCCESS";
export const GET_ALL_ADMIN_FAIL = "GET_ALL_ADMIN_FAIL";

export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

export const UPDATE_ADMIN_DETAILS_REQUEST = "UPDATE_ADMIN_DETAILS_REQUEST";
export const UPDATE_ADMIN_DETAILS_SUCCESS = "UPDATE_ADMIN_DETAILS_SUCCESS";
export const UPDATE_ADMIN_DETAILS_FAIL = "UPDATE_ADMIN_DETAILS_FAIL";
