export const GET_ALL_ADMIN_USERS_REQUEST = "GET_ALL_ADMIN_USERS_REQUEST";
export const GET_ALL_ADMIN_USERS_SUCCESS = "GET_ALL_ADMIN_USERS_SUCCESS";
export const GET_ALL_ADMIN_USERS_FAIL = "GET_ALL_ADMIN_USERS_FAIL";

export const ASSIGN_PERMISSIONS_REQUEST = "ASSIGN_PERMISSIONS_REQUEST";
export const ASSIGN_PERMISSIONS_SUCCESS = "ASSIGN_PERMISSIONS_SUCCESS";
export const ASSIGN_PERMISSIONS_FAIL = "ASSIGN_PERMISSIONS_FAIL";

export const GET_ADMIN_PERMISSIONS_REQUEST = "GET_ADMIN_PERMISSIONS_REQUEST";
export const GET_ADMIN_PERMISSIONS_SUCCESS = "GET_ADMIN_PERMISSIONS_SUCCESS";
export const GET_ADMIN_PERMISSIONS_FAIL = "GET_ADMIN_PERMISSIONS_FAIL";
