export const GET_ALL_BLOG_CATEGORY_REQUEST = "GET_ALL_BLOG_CATEGORY_REQUEST";
export const GET_ALL_BLOG_CATEGORY_SUCCESS = "GET_ALL_BLOG_CATEGORY_SUCCESS";
export const GET_ALL_BLOG_CATEGORY_FAIL = "GET_ALL_BLOG_CATEGORY_FAIL";

export const CREATE_BLOG_CATEGORY_REQUEST = "CREATE_BLOG_CATEGORY_REQUEST";
export const CREATE_BLOG_CATEGORY_SUCCESS = "CREATE_BLOG_CATEGORY_SUCCESS";
export const CREATE_BLOG_CATEGORY_FAIL = "CREATE_BLOG_CATEGORY_FAIL";

export const DELETE_BLOG_CATEGORY_REQUEST = "DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAIL = "DELETE_BLOG_CATEGORY_FAIL";

export const GET_BLOG_CATEGORY_DETAILS_REQUEST =
  "GET_BLOG_CATEGORY_DETAILS_REQUEST";
export const GET_BLOG_CATEGORY_DETAILS_SUCCESS =
  "GET_BLOG_CATEGORY_DETAILS_SUCCESS";
export const GET_BLOG_CATEGORY_DETAILS_FAIL = "GET_BLOG_CATEGORY_DETAILS_FAIL";

export const UPDATE_BLOG_CATEGORY_REQUEST = "UPDATE_BLOG_CATEGORY_REQUEST";
export const UPDATE_BLOG_CATEGORY_SUCCESS = "UPDATE_BLOG_CATEGORY_SUCCESS";
export const UPDATE_BLOG_CATEGORY_FAIL = "UPDATE_BLOG_CATEGORY_FAIL";
