export const GET_ALL_CONTACT_US_REQUEST = "GET_ALL_CONTACT_US_REQUEST";
export const GET_ALL_CONTACT_US_SUCCESS = "GET_ALL_CONTACT_US_SUCCESS";
export const GET_ALL_CONTACT_US_FAIL = "GET_ALL_CONTACT_US_FAIL";

export const GET_CONTACT_US_DETAILS_REQUEST = "GET_CONTACT_US_DETAILS_REQUEST";
export const GET_CONTACT_US_DETAILS_SUCCESS = "GET_CONTACT_US_DETAILS_SUCCESS";
export const GET_CONTACT_US_DETAILS_FAIL = "GET_CONTACT_US_DETAILS_FAIL";

export const DELETE_CONTACT_US_DETAILS_REQUEST =
  "DELETE_CONTACT_US_DETAILS_REQUEST";
export const DELETE_CONTACT_US_DETAILS_SUCCESS =
  "DELETE_CONTACT_US_DETAILS_SUCCESS";
export const DELETE_CONTACT_US_DETAILS_FAIL = "DELETE_CONTACT_US_DETAILS_FAIL";
