export const GET_GUEST_USERS_REVIEWS_REQUEST =
  "GET_GUEST_USERS_REVIEWS_REQUEST";
export const GET_GUEST_USERS_REVIEWS_SUCCESS =
  "GET_GUEST_USERS_REVIEWS_SUCCESS";
export const GET_GUEST_USERS_REVIEWS_FAIL = "GET_GUEST_USERS_REVIEWS_FAIL";

export const DELETE_GUEST_USERS_REVIEW_REQUEST =
  "DELETE_GUEST_USERS_REVIEW_REQUEST";
export const DELETE_GUEST_USERS_REVIEW_SUCCESS =
  "DELETE_GUEST_USERS_REVIEW_SUCCESS";
export const DELETE_GUEST_USERS_REVIEW_FAIL = "DELETE_GUEST_USERS_REVIEW_FAIL";

export const APPROVE_GUEST_USERS_REVIEW_REQUEST =
  "APPROVE_GUEST_USERS_REVIEW_REQUEST";
export const APPROVE_GUEST_USERS_REVIEW_SUCCESS =
  "APPROVE_GUEST_USERS_REVIEW_SUCCESS";
export const APPROVE_GUEST_USERS_REVIEW_FAIL =
  "APPROVE_GUEST_USERS_REVIEW_FAIL";
