// constants/actionTypes.js
export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const FETCH_PENDING_ORDERS_REQUEST = "FETCH_PENDING_ORDERS_REQUEST";
export const FETCH_PENDING_ORDERS_SUCCESS = "FETCH_PENDING_ORDERS_SUCCESS";
export const FETCH_PENDING_ORDERS_FAILURE = "FETCH_PENDING_ORDERS_FAILURE";

export const FETCH_COMPLETED_ORDERS_REQUEST = "FETCH_COMPLETED_ORDERS_REQUEST";
export const FETCH_COMPLETED_ORDERS_SUCCESS = "FETCH_COMPLETED_ORDERS_SUCCESS";
export const FETCH_COMPLETED_ORDERS_FAILURE = "FETCH_COMPLETED_ORDERS_FAILURE";

export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILURE = "FETCH_ORDER_FAILURE";

export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_REQUEST =
  "GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_REQUEST";
export const GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_SUCCESS =
  "GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_SUCCESS";
export const GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_FAIL =
  "GET_ALL_KIND_ORDERS_COUNT_AND_RECENT_ORDERS_FAILURE";
