export const GET_ABOUT_US_PAGE_DETAILS_REQUEST =
  "GET_ABOUT_US_PAGE_DETAILS_REQUEST";
export const GET_ABOUT_US_PAGE_DETAILS_SUCCESS =
  "GET_ABOUT_US_PAGE_DETAILS_SUCCESS";
export const GET_ABOUT_US_PAGE_DETAILS_FAIL = "GET_ABOUT_US_PAGE_DETAILS_FAIL";

export const GET_ABOUT_US_META_DATA_REQUEST = "GET_ABOUT_US_META_DATA_REQUEST";
export const GET_ABOUT_US_META_DATA_SUCCESS = "GET_ABOUT_US_META_DATA_SUCCESS";
export const GET_ABOUT_US_META_DATA_FAIL = "GET_ABOUT_US_META_DATA_FAIL";
