export const GET_ALL_BLOG_REQUEST = "GET_ALL_BLOG_REQUEST";
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_FAIL = "GET_ALL_BLOG_FAIL";

export const GET_ALL_BLOG_CATEGORY_REQUEST = "GET_ALL_BLOG_CATEGORY_REQUEST";
export const GET_ALL_BLOG_CATEGORY_SUCCESS = "GET_ALL_BLOG_CATEGORY_SUCCESS";
export const GET_ALL_BLOG_CATEGORY_FAIL = "GET_ALL_BLOG_CATEGORY_FAIL";

export const GET_BLOGS_META_DATA_REQUEST = "GET_BLOGS_META_DATA_REQUEST";
export const GET_BLOGS_META_DATA_SUCCESS = "GET_BLOGS_META_DATA_SUCCESS";
export const GET_BLOGS_META_DATA_FAIL = "GET_BLOGS_META_DATA_FAIL";

export const GET_BLOG_META_DATA_REQUEST = "GET_BLOG_META_DATA_REQUEST";
export const GET_BLOG_META_DATA_SUCCESS = "GET_BLOG_META_DATA_SUCCESS";
export const GET_BLOG_META_DATA_FAIL = "GET_BLOG_META_DATA_FAIL";

export const GET_BLOG_DETAILS_REQUEST = "GET_BLOG_DETAILS_REQUEST";
export const GET_BLOG_DETAILS_SUCCESS = "GET_BLOG_DETAILS_SUCCESS";
export const GET_BLOG_DETAILS_FAIL = "GET_BLOG_DETAILS_FAIL";

export const GET_BLOGS_FOR_HOME_REQUEST = "GET_BLOGS_FOR_HOME_REQUEST";
export const GET_BLOGS_FOR_HOME_SUCCESS = "GET_BLOGS_FOR_HOME_SUCCESS";
export const GET_BLOGS_FOR_HOME_FAIL = "GET_BLOGS_FOR_HOME_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
