export const ADD_PRODUCT_ITEM_IN_CART_REQUEST =
  "ADD_PRODUCT_ITEM_IN_CART_REQUEST";
export const ADD_PRODUCT_ITEM_IN_CART_SUCCESS =
  "ADD_PRODUCT_ITEM_IN_CART_SUCCESS";
export const ADD_PRODUCT_ITEM_IN_CART_FAIL = "ADD_PRODUCT_ITEM_IN_CART_FAIL";

export const GET_ALL_CART_PRODUCT_ITEMS_REQUEST =
  "GET_ALL_CART_PRODUCT_ITEMS_REQUEST";
export const GET_ALL_CART_PRODUCT_ITEMS_SUCCESS =
  "GET_ALL_CART_PRODUCT_ITEMS_SUCCESS";
export const GET_ALL_CART_PRODUCT_ITEMS_FAIL =
  "GET_ALL_CART_PRODUCT_ITEMS_FAIL";

export const DELETE_PRODUCT_ITEM_IN_CART_REQUEST =
  "DELETE_PRODUCT_ITEM_IN_CART_REQUEST";
export const DELETE_PRODUCT_ITEM_IN_CART_SUCCESS =
  "DELETE_PRODUCT_ITEM_IN_CART_SUCCESS";
export const DELETE_PRODUCT_ITEM_IN_CART_FAIL =
  "DELETE_PRODUCT_ITEM_IN_CART_FAIL";

export const EMPTY_CART_REQUEST = "EMPTY_CART_REQUEST";
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";
export const EMPTY_CART_FAIL = "EMPTY_CART_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
