export const GET_CATEGORIES_PAGE_BANNERS_DETAILS_REQUEST =
  "GET_CATEGORIES_PAGE_BANNERS_DETAILS_REQUEST";
export const GET_CATEGORIES_PAGE_BANNERS_DETAILS_SUCCESS =
  "GET_CATEGORIES_PAGE_BANNERS_DETAILS_SUCCESS";
export const GET_CATEGORIES_PAGE_BANNERS_DETAILS_FAIL =
  "GET_CATEGORIES_PAGE_BANNERS_DETAILS_FAIL";
