export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const GET_CATEGORIES_META_DATA_REQUEST =
  "GET_CATEGORIES_META_DATA_REQUEST";
export const GET_CATEGORIES_META_DATA_SUCCESS =
  "GET_CATEGORIES_META_DATA_SUCCESS";
export const GET_CATEGORIES_META_DATA_FAIL = "GET_CATEGORIES_META_DATA_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
