export const CREATE_CONTACT_US_REQUEST = "CREATE_CONTACT_US_REQUEST";
export const CREATE_CONTACT_US_SUCCESS = "CREATE_CONTACT_US_SUCCESS";
export const CREATE_CONTACT_US_FAIL = "CREATE_CONTACT_US_FAIL";

export const GET_CONTACT_US_META_DATA_REQUEST =
  "GET_CONTACT_US_META_DATA_REQUEST";
export const GET_CONTACT_US_META_DATA_SUCCESS =
  "GET_CONTACT_US_META_DATA_SUCCESS";
export const GET_CONTACT_US_META_DATA_FAIL = "GET_CONTACT_US_META_DATA_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
