export const GET_ALL_COUPON_REQUEST = "GET_ALL_COUPON_REQUEST";
export const GET_ALL_COUPON_SUCCESS = "GET_ALL_COUPON_SUCCESS";
export const GET_ALL_COUPON_FAIL = "GET_ALL_COUPON_FAIL";

export const COUPON_APPLY_REQUEST = "COUPON_APPLY_REQUEST";
export const COUPON_APPLY_SUCCESS = "COUPON_APPLY_SUCCESS";
export const COUPON_APPLY_FAIL = "COUPON_APPLY_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
