export const GET_ALL_FAQ_FAIL = "GET_ALL_FAQ_FAIL";
export const GET_ALL_FAQ_REQUEST = "GET_ALL_FAQ_REQUEST";
export const GET_ALL_FAQ_SUCCESS = "GET_ALL_FAQ_SUCCESS";

export const GET_FAQ_DETAILS_REQUEST = "GET_FAQ_DETAILS_REQUEST";
export const GET_FAQ_DETAILS_SUCCESS = "GET_FAQ_DETAILS_SUCCESS";
export const GET_FAQ_DETAILS_FAIL = "GET_FAQ_DETAILS_FAIL";
