export const GET_HOMES_META_DATA_REQUEST = "GET_HOMES_META_DATA_REQUEST";
export const GET_HOMES_META_DATA_SUCCESS = "GET_HOMES_META_DATA_SUCCESS";
export const GET_HOMES_META_DATA_FAIL = "GET_HOMES_META_DATA_FAIL";
