export const GET_HOME_PAGE_BANNERS_DETAILS_REQUEST =
  "GET_HOME_PAGE_BANNERS_DETAILS_REQUEST";
export const GET_HOME_PAGE_BANNERS_DETAILS_SUCCESS =
  "GET_HOME_PAGE_BANNERS_DETAILS_SUCCESS";
export const GET_HOME_PAGE_BANNERS_DETAILS_FAIL =
  "GET_HOME_PAGE_BANNERS_DETAILS_FAIL";
