export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";

export const COMPARE_OTP_REQUEST = "COMPARE_OTP_REQUEST";
export const COMPARE_OTP_SUCCESS = "COMPARE_OTP_SUCCESS";
export const COMPARE_OTP_FAIL = "COMPARE_OTP_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
