export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

export const GET_ALL_BEST_SELLERS_PRODUCT_REQUEST =
  "GET_ALL_BEST_SELLERS_PRODUCT_REQUEST";
export const GET_ALL_BEST_SELLERS_PRODUCT_SUCCESS =
  "GET_ALL_BEST_SELLERS_PRODUCT_SUCCESS";
export const GET_ALL_BEST_SELLERS_PRODUCT_FAIL =
  "GET_ALL_BEST_SELLERS_PRODUCT_FAIL";

export const GET_ALL_BEST_OFFERS_PRODUCT_REQUEST =
  "GET_ALL_BEST_OFFERS_PRODUCT_REQUEST";
export const GET_ALL_BEST_OFFERS_PRODUCT_SUCCESS =
  "GET_ALL_BEST_OFFERS_PRODUCT_SUCCESS";
export const GET_ALL_BEST_OFFERS_PRODUCT_FAIL =
  "GET_ALL_BEST_OFFERS_PRODUCT_FAIL";

export const GET_ALL_FEATURED_PRODUCTS_REQUEST =
  "GET_ALL_FEATURED_PRODUCTS_REQUEST";
export const GET_ALL_FEATURED_PRODUCTS_SUCCESS =
  "GET_ALL_FEATURED_PRODUCTS_SUCCESS";
export const GET_ALL_FEATURED_PRODUCTS_FAIL = "GET_ALL_FEATURED_PRODUCTS_FAIL";

export const GET_SHOP_ALL_META_DATA_REQUEST = "GET_SHOP_ALL_META_DATA_REQUEST";
export const GET_SHOP_ALL_META_DATA_SUCCESS = "GET_SHOP_ALL_META_DATA_SUCCESS";
export const GET_SHOP_ALL_META_DATA_FAIL = "GET_SHOP_ALL_META_DATA_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
