export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";
export const CREATE_AND_UPDATE_REQUEST = "CREATE_AND_UPDATE_REQUEST";
export const CREATE_AND_UPDATE_SUCCESS = "CREATE_AND_UPDATE_SUCCESS";
export const CREATE_AND_UPDATE_FAIL = "CREATE_AND_UPDATE_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
