export const SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_REQUEST =
  "SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_REQUEST";
export const SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_SUCCESS =
  "SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_SUCCESS";
export const SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_FAIL =
  "SELECT_SHIPPING_ADDRESS_FOR_LOGIN_USER_FAIL";

export const GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_REQUEST =
  "GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_REQUEST";
export const GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_SUCCESS =
  "GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_SUCCESS";
export const GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_FAIL =
  "GET_SELECTED_SHIPPING_ADDRESS_FOR_LOGIN_USER_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
