export const GET_SHOP_ALL_PAGE_BANNERS_DETAILS_REQUEST =
  "GET_SHOP_ALL_PAGE_BANNERS_DETAILS_REQUEST";
export const GET_SHOP_ALL_PAGE_BANNERS_DETAILS_SUCCESS =
  "GET_SHOP_ALL_PAGE_BANNERS_DETAILS_SUCCESS";
export const GET_SHOP_ALL_PAGE_BANNERS_DETAILS_FAIL =
  "GET_SHOP_ALL_PAGE_BANNERS_DETAILS_FAIL";
