export const GET_ALL_WISHLISTS_PRODUCTS_REQUEST =
  "GET_ALL_WISHLISTS_PRODUCTS_REQUEST";
export const GET_ALL_WISHLISTS_PRODUCTS_SUCCESS =
  "GET_ALL_WISHLISTS_PRODUCTS_SUCCESS";
export const GET_ALL_WISHLISTS_PRODUCTS_FAIL =
  "GET_ALL_WISHLISTS_PRODUCTS_FAIL";

export const ADD_WISHLIST_PRODUCT_REQUEST = "ADD_WISHLIST_PRODUCT_REQUEST";
export const ADD_WISHLIST_PRODUCT_SUCCESS = "ADD_WISHLIST_PRODUCT_SUCCESS";
export const ADD_WISHLIST_PRODUCT_FAIL = "ADD_WISHLIST_PRODUCT_FAIL";

export const DELETE_WISHLIST_ITEM_REQUEST = "DELETE_WISHLIST_ITEM_REQUEST";
export const DELETE_WISHLIST_ITEM_SUCCESS = "DELETE_WISHLIST_ITEM_SUCCESS";
export const DELETE_WISHLIST_ITEM_FAIL = "DELETE_WISHLIST_ITEM_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
