export const CREATE_ABOUT_US_PAGE_REQUEST = "CREATE_ABOUT_US_PAGE_REQUEST";
export const CREATE_ABOUT_US_PAGE_SUCCESS = "CREATE_ABOUT_US_PAGE_SUCCESS";
export const CREATE_ABOUT_US_PAGE_FAIL = "CREATE_ABOUT_US_PAGE_FAIL";

export const GET_ABOUT_US_PAGE_DETAILS_REQUEST =
  "GET_ABOUT_US_PAGE_DETAILS_REQUEST";
export const GET_ABOUT_US_PAGE_DETAILS_SUCCESS =
  "GET_ABOUT_US_PAGE_DETAILS_SUCCESS";
export const GET_ABOUT_US_PAGE_DETAILS_FAIL = "GET_ABOUT_US_PAGE_DETAILS_FAIL";

export const UPDATE_ABOUT_US_PAGE_DETAILS_REQUEST =
  "UPDATE_ABOUT_US_PAGE_DETAILS_REQUEST";
export const UPDATE_ABOUT_US_PAGE_DETAILS_SUCCESS =
  "UPDATE_ABOUT_US_PAGE_DETAILS_SUCCESS";
export const UPDATE_ABOUT_US_PAGE_DETAILS_FAIL =
  "UPDATE_ABOUT_US_PAGE_DETAILS_FAIL";
