export const CREATE_FAQ_REQUEST = "CREATE_FAQ_REQUEST";
export const CREATE_FAQ_SUCCESS = "CREATE_FAQ_SUCCESS";
export const CREATE_FAQ_FAIL = "CREATE_FAQ_FAIL";

export const GET_FAQ_DETAILS_REQUEST = "GET_FAQ_DETAILS_REQUEST";
export const GET_FAQ_DETAILS_SUCCESS = "GET_FAQ_DETAILS_SUCCESS";
export const GET_FAQ_DETAILS_FAIL = "GET_FAQ_DETAILS_FAIL";

export const UPDATE_FAQ_DETAILS_REQUEST = "UPDATE_FAQ_DETAILS_REQUEST";
export const UPDATE_FAQ_DETAILS_SUCCESS = "UPDATE_FAQ_DETAILS_SUCCESS";
export const UPDATE_FAQ_DETAILS_FAIL = "UPDATE_FAQ_DETAILS_FAIL";

export const GET_ALL_FAQ_FAIL = "GET_ALL_FAQ_FAIL";
export const GET_ALL_FAQ_REQUEST = "GET_ALL_FAQ_REQUEST";
export const GET_ALL_FAQ_SUCCESS = "GET_ALL_FAQ_SUCCESS";

export const DELETE_FAQ_REQUEST = "DELETE _FAQ_REQUEST";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";
