export const CREATE_HOME_PAGE_BANNERS_REQUEST =
  "CREATE_HOME_PAGE_BANNERS_REQUEST";
export const CREATE_HOME_PAGE_BANNERS_SUCCESS =
  "CREATE_HOME_PAGE_BANNERS_SUCCESS";
export const CREATE_HOME_PAGE_BANNERS_FAIL = "CREATE_HOME_PAGE_BANNERS_FAIL";

export const GET_HOME_PAGE_BANNERS_DETAILS_REQUEST =
  "GET_HOME_PAGE_BANNERS_DETAILS_REQUEST";
export const GET_HOME_PAGE_BANNERS_DETAILS_SUCCESS =
  "GET_HOME_PAGE_BANNERS_DETAILS_SUCCESS";
export const GET_HOME_PAGE_BANNERS_DETAILS_FAIL =
  "GET_HOME_PAGE_BANNERS_DETAILS_FAIL";

export const UPDATE_HOME_PAGE_BANNERS_DETAILS_REQUEST =
  "UPDATE_HOME_PAGE_BANNERS_DETAILS_REQUEST";
export const UPDATE_HOME_PAGE_BANNERS_DETAILS_SUCCESS =
  "UPDATE_HOME_PAGE_BANNERS_DETAILS_SUCCESS";
export const UPDATE_HOME_PAGE_BANNERS_DETAILS_FAIL =
  "UPDATE_HOME_PAGE_BANNERS_DETAILS_FAIL";
