const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    firstName: {
      type: String,
      required: true,
    },
    lastName: {
      type: String,
      required: true,
    },
    mobileNumber: {
      type: String,

      required: false,
      unique: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    addresses: [
      {
        firstName: {
          type: String,
          required: true,
        },
        lastName: {
          type: String,
          required: true,
        },
        phone: {
          type: String,

          required: false,
        },
        street: { type: String, required: true },
        city: { type: String, required: true },
        state: { type: String, required: true },
        zipCode: { type: String, required: true },
        country: { type: String, required: true },
        isDefault: { type: Boolean, default: false },
      },
    ],
    permissions: [
      {
        createProducts: { type: Boolean, required: false },
        readProducts: { type: Boolean, required: false },
        updateProducts: { type: Boolean, required: false },
        deleteProducts: { type: Boolean, required: false },
        createCoupons: { type: Boolean, required: false },
        readCoupons: { type: Boolean, required: false },
        updateCoupons: { type: Boolean, required: false },
        deleteCoupons: { type: Boolean, required: false },
        createOrders: { type: Boolean, required: false },
        readOrders: { type: Boolean, required: false },
        updateOrders: { type: Boolean, required: false },
        deleteOrders: { type: Boolean, required: false },
        createContactUs: { type: Boolean, required: false },
        readContactUs: { type: Boolean, required: false },
        updateContactUs: { type: Boolean, required: false },
        deleteContactUs: { type: Boolean, required: false },
        createBlogs: { type: Boolean, required: false },
        readBlogs: { type: Boolean, required: false },
        updateBlogs: { type: Boolean, required: false },
        deleteBlogs: { type: Boolean, required: false },
        createCategories: { type: Boolean, required: false },
        readCategories: { type: Boolean, required: false },
        updateCategories: { type: Boolean, required: false },
        deleteCategories: { type: Boolean, required: false },
        createSubCategories: { type: Boolean, required: false },
        readSubCategories: { type: Boolean, required: false },
        updateSubCategories: { type: Boolean, required: false },
        deleteSubCategories: { type: Boolean, required: false },
        createCustomers: { type: Boolean, required: false },
        readCustomers: { type: Boolean, required: false },
        updateCustomers: { type: Boolean, required: false },
        deleteCustomers: { type: Boolean, required: false },
        createAboutUsDg: { type: Boolean, required: false },
        readAboutUsDg: { type: Boolean, required: false },
        updateAboutUsDg: { type: Boolean, required: false },
        createContactUsDg: { type: Boolean, required: false },
        readContactUsDg: { type: Boolean, required: false },
        updateContactUsDg: { type: Boolean, required: false },
        createBlogDg: { type: Boolean, required: false },
        readBlogDg: { type: Boolean, required: false },
        updateBlogDg: { type: Boolean, required: false },
        createFaqDg: { type: Boolean, required: false },
        readFaqDg: { type: Boolean, required: false },
        updateFaqDg: { type: Boolean, required: false },
        createHomePageDg: { type: Boolean, required: false },
        readHomePageDg: { type: Boolean, required: false },
        updateHomePageDg: { type: Boolean, required: false },
        createPackagingAndAuthenticationDg: { type: Boolean, required: false },
        readPackagingAndAuthenticationDg: { type: Boolean, required: false },
        updatePackagingAndAuthenticationDg: { type: Boolean, required: false },
        createPrivacyPolicyDg: { type: Boolean, required: false },
        readPrivacyPolicyDg: { type: Boolean, required: false },
        updatePrivacyPolicyDg: { type: Boolean, required: false },
        createShopAllDg: { type: Boolean, required: false },
        readShopAllDg: { type: Boolean, required: false },
        updateShopAllDg: { type: Boolean, required: false },
        createAboutUsPg: { type: Boolean, required: false },
        readAboutUsPg: { type: Boolean, required: false },
        updateAboutUsPg: { type: Boolean, required: false },
        deleteAboutUsPg: { type: Boolean, required: false },
        createBlogCategories: { type: Boolean, required: false },
        readBlogCategories: { type: Boolean, required: false },
        updateBlogCategories: { type: Boolean, required: false },
        deleteBlogCategories: { type: Boolean, required: false },
        createCategoriesPg: { type: Boolean, required: false },
        readCategoriesPg: { type: Boolean, required: false },
        updateCategoriesPg: { type: Boolean, required: false },
        deleteCategoriesPg: { type: Boolean, required: false },
        createFaqsPg: { type: Boolean, required: false },
        readFaqsPg: { type: Boolean, required: false },
        updateFaqsPg: { type: Boolean, required: false },
        deleteFaqsPg: { type: Boolean, required: false },
        createHomePagePg: { type: Boolean, required: false },
        readHomePagePg: { type: Boolean, required: false },
        updateHomePagePg: { type: Boolean, required: false },
        deleteHomePagePg: { type: Boolean, required: false },
        createPackageAndAuthenticityPg: { type: Boolean, required: false },
        readPackageAndAuthenticityPg: { type: Boolean, required: false },
        updatePackageAndAuthenticityPg: { type: Boolean, required: false },
        deletePackageAndAuthenticityPg: { type: Boolean, required: false },
        createPrivacyPolicyPg: { type: Boolean, required: false },
        readPrivacyPolicyPg: { type: Boolean, required: false },
        updatePrivacyPolicyPg: { type: Boolean, required: false },
        deletePrivacyPolicyPg: { type: Boolean, required: false },
        createShopAllPg: { type: Boolean, required: false },
        readShopAllPg: { type: Boolean, required: false },
        updateShopAllPg: { type: Boolean, required: false },
        deleteShopAllPg: { type: Boolean, required: false },
      },
    ],
    roles: {
      type: String,
      required: false,
      enum: ["SUPPORT", "MARKETING"],
    },
    isAdmin: {
      type: Boolean,
      default: false,
    },
    isSuperAdmin: {
      type: Boolean,
      default: false,
    },
    avatar: {
      type: String,
      required: false,
    },
    // isMarketer: {
    //   type: Boolean,
    //   default: false,
    // },
    // isSupport: {
    //   type: Boolean,
    //   default: false,
    // },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("User", userSchema);
