export const CREATE_BLOG_PAGE_REQUEST = "CREATE_BLOG_PAGE_REQUEST";
export const CREATE_BLOG_PAGE_SUCCESS = "CREATE_BLOG_PAGE_SUCCESS";
export const CREATE_BLOG_PAGE_FAIL = "CREATE_BLOG_PAGE_FAIL";

export const GET_BLOG_PAGE_DETAILS_REQUEST = "GET_BLOG_PAGE_DETAILS_REQUEST";
export const GET_BLOG_PAGE_DETAILS_SUCCESS = "GET_BLOG_PAGE_DETAILS_SUCCESS";
export const GET_BLOG_PAGE_DETAILS_FAIL = "GET_BLOG_PAGE_DETAILS_FAIL";

export const UPDATE_BLOG_PAGE_DETAILS_REQUEST =
  "UPDATE_BLOG_PAGE_DETAILS_REQUEST";
export const UPDATE_BLOG_PAGE_DETAILS_SUCCESS =
  "UPDATE_BLOG_PAGE_DETAILS_SUCCESS";
export const UPDATE_BLOG_PAGE_DETAILS_FAIL = "UPDATE_BLOG_PAGE_DETAILS_FAIL";
