export const CREATE_CATEGORY_PAGE_REQUEST = "CREATE_CATEGORY_PAGE_REQUEST";
export const CREATE_CATEGORY_PAGE_SUCCESS = "CREATE_CATEGORY_PAGE_SUCCESS";
export const CREATE_CATEGORY_PAGE_FAIL = "CREATE_CATEGORY_PAGE_FAIL";

export const GET_CATEGORY_PAGE_DETAILS_REQUEST =
  "GET_CATEGORY_PAGE_DETAILS_REQUEST";
export const GET_CATEGORY_PAGE_DETAILS_SUCCESS =
  "GET_CATEGORY_PAGE_DETAILS_SUCCESS";
export const GET_CATEGORY_PAGE_DETAILS_FAIL = "GET_CATEGORY_PAGE_DETAILS_FAIL";

export const UPDATE_CATEGORY_PAGE_DETAILS_REQUEST =
  "UPDATE_CATEGORY_PAGE_DETAILS_REQUEST";
export const UPDATE_CATEGORY_PAGE_DETAILS_SUCCESS =
  "UPDATE_CATEGORY_PAGE_DETAILS_SUCCESS";
export const UPDATE_CATEGORY_PAGE_DETAILS_FAIL =
  "UPDATE_CATEGORY_PAGE_DETAILS_FAIL";
