export const CREATE_CONTACT_US_PAGE_REQUEST = "CREATE_CONTACT_US_REQUEST";
export const CREATE_CONTACT_US_PAGE_SUCCESS = "CREATE_CONTACT_US_SUCCESS";
export const CREATE_CONTACT_US_PAGE_FAIL = "CREATE_CONTACT_US_FAIL";

export const GET_CONTACT_US_PAGE_DETAILS_REQUEST =
  "GET_CONTACT_US_PAGE_DETAILS_REQUEST";
export const GET_CONTACT_US_PAGE_DETAILS_SUCCESS =
  "GET_CONTACT_US_PAGE_DETAILS_SUCCESS";
export const GET_CONTACT_US_PAGE_DETAILS_FAIL =
  "GET_CONTACT_US_PAGE_DETAILS_FAIL";

export const UPDATE_CONTACT_US_PAGE_DETAILS_REQUEST =
  "UPDATE_CONTACT_US_PAGE_DETAILS_REQUEST";
export const UPDATE_CONTACT_US_PAGE_DETAILS_SUCCESS =
  "UPDATE_CONTACT_US_PAGE_DETAILS_SUCCESS";
export const UPDATE_CONTACT_US_PAGE_DETAILS_FAIL =
  "UPDATE_CONTACT_US_PAGE_DETAILS_FAIL";
