export const CREATE_FAQ_PAGE_REQUEST = "CREATE_FAQ_PAGE_REQUEST";
export const CREATE_FAQ_PAGE_SUCCESS = "CREATE_FAQ_PAGE_SUCCESS";
export const CREATE_FAQ_PAGE_FAIL = "CREATE_FAQ_PAGE_FAIL";

export const GET_FAQ_PAGE_DETAILS_REQUEST = "GET_FAQ_PAGE_DETAILS_REQUEST";
export const GET_FAQ_PAGE_DETAILS_SUCCESS = "GET_FAQ_PAGE_DETAILS_SUCCESS";
export const GET_FAQ_PAGE_DETAILS_FAIL = "GET_FAQ_PAGE_DETAILS_FAIL";

export const UPDATE_FAQ_PAGE_DETAILS_REQUEST =
  "UPDATE_FAQ_PAGE_DETAILS_REQUEST";
export const UPDATE_FAQ_PAGE_DETAILS_SUCCESS =
  "UPDATE_FAQ_PAGE_DETAILS_SUCCESS";
export const UPDATE_FAQ_PAGE_DETAILS_FAIL = "UPDATE_FAQ_PAGE_DETAILS_FAIL";
