export const CREATE_PACKAGE_AND_AUTHENTICITY_REQUEST =
  "CREATE_PACKAGE_AND_AUTHENTICITY_REQUEST";
export const CREATE_PACKAGE_AND_AUTHENTICITY_SUCCESS =
  "CREATE_PACKAGE_AND_AUTHENTICITY_SUCCESS";
export const CREATE_PACKAGE_AND_AUTHENTICITY_FAIL =
  "CREATE_PACKAGE_AND_AUTHENTICITY_FAIL";

export const GET_PACKAGE_AND_AUTHENTICITY_DETAILS_REQUEST =
  "GET_PACKAGE_AND_AUTHENTICITY_DETAILS_REQUEST";
export const GET_PACKAGE_AND_AUTHENTICITY_DETAILS_SUCCESS =
  "GET_PACKAGE_AND_AUTHENTICITY_DETAILS_SUCCESS";
export const GET_PACKAGE_AND_AUTHENTICITY_DETAILS_FAIL =
  "GET_PACKAGE_AND_AUTHENTICITY_DETAILS_FAIL";

export const UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_REQUEST =
  "UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_REQUEST";
export const UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_SUCCESS =
  "UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_SUCCESS";
export const UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_FAIL =
  "UPDATE_PACKAGE_AND_AUTHENTICITY_DETAILS_FAIL";
