export const CREATE_PRIVACY_PAGE_REQUEST = "CREATE_PRIVACY_PAGE_REQUEST";
export const CREATE_PRIVACY_PAGE_SUCCESS = "CREATE_PRIVACY_PAGE_SUCCESS";
export const CREATE_PRIVACY_PAGE_FAIL = "CREATE_PRIVACY_PAGE_FAIL";

export const GET_PRIVACY_POLICY_PAGE_DETAILS_REQUEST =
  "GET_PRIVACY_POLICY_PAGE_DETAILS_REQUEST";
export const GET_PRIVACY_POLICY_PAGE_DETAILS_SUCCESS =
  "GET_PRIVACY_POLICY_PAGE_DETAILS_SUCCESS";
export const GET_PRIVACY_POLICY_PAGE_DETAILS_FAIL =
  "GET_PRIVACY_POLICY_PAGE_DETAILS_FAIL";

export const UPDATE_PRIVACY_POLICY_PAGE_DETAILS_REQUEST =
  "UPDATE_PRIVACY_POLICY_PAGE_DETAILS_REQUEST";
export const UPDATE_PRIVACY_POLICY_PAGE_DETAILS_SUCCESS =
  "UPDATE_PRIVACY_POLICY_PAGE_DETAILS_SUCCESS";
export const UPDATE_PRIVACY_POLICY_PAGE_DETAILS_FAIL =
  "UPDATE_PRIVACY_POLICY_PAGE_DETAILS_FAIL";
