export const CREATE_SHOP_ALL_REQUEST = "CREATE_SHOP_ALL_REQUEST";
export const CREATE_SHOP_ALL_SUCCESS = "CREATE_SHOP_ALL_SUCCESS";
export const CREATE_SHOP_ALL_FAIL = "CREATE_SHOP_ALL_FAIL";

export const GET_SHOP_ALL_PAGE_DETAILS_REQUEST =
  "GET_SHOP_ALL_PAGE_DETAILS_REQUEST";
export const GET_SHOP_ALL_PAGE_DETAILS_SUCCESS =
  "GET_SHOP_ALL_PAGE_DETAILS_SUCCESS";
export const GET_SHOP_ALL_PAGE_DETAILS_FAIL = "GET_SHOP_ALL_PAGE_DETAILS_FAIL";

export const UPDATE_SHOP_ALL_PAGE_DETAILS_REQUEST =
  "UPDATE_SHOP_ALL_PAGE_DETAILS_REQUEST";
export const UPDATE_SHOP_ALL_PAGE_DETAILS_SUCCESS =
  "UPDATE_SHOP_ALL_PAGE_DETAILS_SUCCESS";
export const UPDATE_SHOP_ALL_PAGE_DETAILS_FAIL =
  "UPDATE_SHOP_ALL_PAGE_DETAILS_FAIL";
